<a href="https://colab.research.google.com/github/LeonardoGoncRibeiro/01_DataScienceUsingPython/blob/main/02_NumpyIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

In this file, numpy library will be introduced. Numpy is a very popular library for data science, as it assists in handling numerical data.

Checking python version

In [23]:
!python -V

Python 3.7.13


# Working with Numpy arrays

In [24]:
import numpy as np

Saving data to python variables

In [143]:
km   = np.loadtxt('car_km.txt', dtype = float)
year = np.loadtxt('car_year.txt', dtype = int)


Assessing measures of central tendency

In [ ]:
km_bar = np.mean(km)
print(f'mean km: {km_bar}')

mean km: 66215.77741935484


Assessing the mean km driven per year for each car

In [ ]:
year_now = 2022
km_per_year = km/(year_now - year)

km_per_year

array([ 4666.66666667,  3333.33333333, 10000.        , ...,
        6384.61538462, 15000.        ,  6666.66666667])

Note that these data hava a specific type related to numpy

In [ ]:
print(type(km_bar))

print(type(km_per_year))

<class 'numpy.float64'>
<class 'numpy.ndarray'>


# Important Python caractheristics

Here, we will show how to perform basic mathematical operations and expressions using Python.

# Mathematical operators

In [ ]:
# addition

2 + 2

4

In [ ]:
# substraction

7-10

-3

In [ ]:
# multiplication

9*4

36

In [ ]:
# division

10/3

3.3333333333333335

In [ ]:
# division (showing only the integer part)

10//3

3

In [ ]:
# exponentiation

2**3

8

In [ ]:
# division (remainder)

10%3

1

# Mathematical expressions

Python considers conventional order for operations (first exponentiation, then multiplication/division, then addition/subtraction)

In [ ]:
5*2 + 3*2

16

We can use paranthesis to change order of operations.

In [ ]:
5*(2 + 3)*2 

50

Variable _ stores the last result printed

In [ ]:
_

50

In [ ]:
_ + 3*2

56

In [ ]:
_/2

28.0

# Variables

In [ ]:
current_year = 2022
car_year_var = 2003
total_km_var = 44410.0

km_avg = total_km_var/(current_year - car_year_var)
print(f'Average: {km_avg} km')

Average: 2337.3684210526317 km


In [ ]:
# Estimating km in 2023

pred_year = 2023

total_km_var += km_avg*(pred_year - current_year) # Important operator! Sequential summation

print(f'We predict that, at {pred_year}, total_km_var: {total_km_var} km')

We predict that, at 2023, total_km_var: 46747.36842105263 km


Declaring multiple variables at once

In [ ]:
current_year, car_year_var, total_km_var, pred_year = 2022, 2003, 44410.0, 2023;

km_avg = total_km_var/(current_year - car_year_var)

total_km_var += km_avg*(pred_year - current_year) # Important operator! Sequential summation

print(f'We predict that, at {pred_year}, total_km_var: {total_km_var} km')

We predict that, at 2023, total_km_var: 46747.36842105263 km


# Variable types

**Numerical data**


1.   **int** - Integers.
2.   **float** - Floating point.

**Booleans** - True or False.

**Strings** - Sequence of characters. Text.

**None** - No value.



In [ ]:
# Numerical data - int

current_year = 2003
type(current_year)

int

In [ ]:
# Numerical data - float

km_total = 44410.0
type(km_total)

float

In [ ]:
# Boolean

is_zero_km = True
type(is_zero_km)

bool

In [ ]:
# String

name = 'Jetta'
type(name)

str

In [ ]:
# None

kilometer = None
type(kilometer)

NoneType

# Type conversion

To better handle data, one might need to convert existing data.

In [ ]:
a, b, c, d, e = 10, 20, 'Python is ', 'cool', 3.14

In [ ]:
a + b

30

In [ ]:
c + d

'Python is cool'

Even though you are able to "sum" two strings or two numerical values, you can not sum a numerical value to a string. Type conversion is necessary to handle these cases.

In [ ]:
c + str(a)

'Python is 10'

However, summation of two numerical values always works (even if one is an integer and the other is a float)

In [ ]:
a + e

13.14

In [ ]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

text + str( Km / (Ano_atual - Ano_fabricacao) ) + ' km'

'A quilometragem média do veículo é 5000.0 km'

# Indentation and commentaries

For python, indentation is very important, as correct indentation is necessary so that loops and conditionals work correctly. 

In [ ]:
curr_year = 2022
fabr_year = 2019

if (curr_year == fabr_year):
  print('New car')
else:
  print('Old car')

Old car


Commentaries, on the other hand, are optional, but it helps other people to understand our code

In [ ]:
# This is a commentary

curr_year = 2022               # Current year
fabr_year = 2019               # Fabrication year

if (curr_year == fabr_year):   # If car was fabricated this year
  print('New car')
else:                          # If not
  print('Old car')

String formatting is useful to print more organized texts.

In [ ]:
print('Hi, {}!'.format('Leonardo'))

Hi, Leonardo!


In [ ]:
print('Hi, {}! This is your access number {}'.format('Leonardo', 32))

Hi, Leonardo! This is your access number 32


In [ ]:
print('Hi, {name}! This is your access number {access}'.format(name = 'Leonardo', access = 32))

Hi, Leonardo! This is your access number 32


In [ ]:
name = 'Leonardo'
access = 32
print(f'Hi, {name}! This is your access number {access}')

Hi, Leonardo! This is your access number 32


# Creating lists

We can create lists using [ ]

Values from the list are separated using comma (,)



In [ ]:
items = ['Cover', 'Cleaning cloth', 'Air freshener', 'Repair kit', 'Tire inflator', 'GPS', 'Tool kit']
items

['Cover',
 'Cleaning cloth',
 'Air freshener',
 'Repair kit',
 'Tire inflator',
 'GPS',
 'Tool kit']

You can create a list **inside** another list.

In [ ]:
car_1 = ['Jetta', '4.0', 2003, 44410.0, False, [items[1], items[4], items[5]], 88078.64]
car_2 = ['Passat', 'Diesel', 1991, 5712.0, False, [items[0], items[2]], 106161.94]

['Passat',
 'Diesel',
 1991,
 5712.0,
 False,
 ['Cover', 'Air freshener'],
 106161.94]

You can even create a list from two (or more) other lists.

In [ ]:
cars = [car_1, car_2]
cars

[['Jetta',
  '4.0',
  2003,
  44410.0,
  False,
  ['Cleaning cloth', 'Tire inflator', 'GPS'],
  88078.64],
 ['Passat',
  'Diesel',
  1991,
  5712.0,
  False,
  ['Cover', 'Air freshener'],
  106161.94]]

# Operations with lists

More extensive documentation can be found in https://docs.python.org/3/tutorial/datastructures.html

In [ ]:
items = ['Cover', 'Cleaning cloth', 'Air freshener', 'Repair kit', 'Tire inflator', 'GPS', 'Tool kit']

Check if an item is (or is not) on the list

In [ ]:
'Air freshener' in items

True

In [ ]:
'Power steering' in items

False

In [ ]:
'Power steering' not in items

True

Concatenating lists

In [ ]:
items_a = ['Cover', 'Cleaning cloth', 'Air freshener', 'Repair kit']
items_b = ['Tire inflator', 'GPS', 'Tool kit']
items = items_a + items_b
items

['Cover',
 'Cleaning cloth',
 'Air freshener',
 'Repair kit',
 'Tire inflator',
 'GPS',
 'Tool kit']

List size

In [ ]:
len(items)

7

# List indexing

List indexing can be performed using [ ]

In [ ]:
items = ['Cover', 'Cleaning cloth', 'Air freshener', 'Repair kit', 'Tire inflator', 'GPS', 'Tool kit']

In [ ]:
items[0]

'Cover'

In [ ]:
items[3]

'Repair kit'

In [ ]:
items[-1]

'Tool kit'

In [ ]:
items[2:5]

['Air freshener', 'Repair kit', 'Tire inflator']

In [ ]:
items[3:]

['Repair kit', 'Tire inflator', 'GPS', 'Tool kit']

We can also perform list indexing when there are list inside other lists

In [ ]:
car_1 = ['Jetta', '4.0', 2003, 44410.0, False, [items[1], items[4], items[5]], 88078.64]
car_2 = ['Passat', 'Diesel', 1991, 5712.0, False, [items[0], items[2]], 106161.94]
cars = [car_1, car_2]

cars[0]

['Jetta',
 '4.0',
 2003,
 44410.0,
 False,
 ['Cleaning cloth', 'Tire inflator', 'GPS'],
 88078.64]

In [ ]:
cars[0][0]

'Jetta'

In [ ]:
cars[0][5]

['Cleaning cloth', 'Tire inflator', 'GPS']

In [ ]:
cars[0][5][-1]

'GPS'

We can slice lists using the correct indexing

In [ ]:
some_items = items[2:5]    # Note that element 2 is included, and element 5 is not.
some_items

['Air freshener', 'Repair kit', 'Tire inflator']

In [ ]:
final_items = items[4:]
some_items

['Air freshener', 'Repair kit', 'Tire inflator']

# Methods using lists

In [ ]:
items = ['Cover', 'Cleaning cloth', 'Air freshener', 'Repair kit', 'Tire inflator', 'GPS', 'Tool kit']

In [ ]:
items.sort( ) # Sort list (in this case, in alphabetical order)
items

['Air freshener',
 'Cleaning cloth',
 'Cover',
 'GPS',
 'Repair kit',
 'Tire inflator',
 'Tool kit']

In [ ]:
items.append('4X4') # Adds a final element
items

['Air freshener',
 'Cleaning cloth',
 'Cover',
 'GPS',
 'Repair kit',
 'Tire inflator',
 'Tool kit',
 '4X4']

In [ ]:
items.pop( ) # Remove final element
items

['Air freshener',
 'Cleaning cloth',
 'Cover',
 'GPS',
 'Repair kit',
 'Tire inflator',
 'Tool kit']

In [ ]:
items.pop(4) # Element index can also be used to remove a specific element
items

['Air freshener',
 'Cleaning cloth',
 'Cover',
 'GPS',
 'Tire inflator',
 'Tool kit']

In [ ]:
items2 = items.copy( ) # Make a copy of a list. Create a new space in the computer memory for the new list.
items2

['Air freshener',
 'Cleaning cloth',
 'Cover',
 'GPS',
 'Tire inflator',
 'Tool kit']

# Loops and conditionals

For operator can be used for simple loops

In [ ]:
items = ['Cover', 'Cleaning cloth', 'Air freshener', 'Repair kit', 'Tire inflator', 'GPS', 'Tool kit']
items

['Cover',
 'Cleaning cloth',
 'Air freshener',
 'Repair kit',
 'Tire inflator',
 'GPS',
 'Tool kit']

In [ ]:
for item in items:
  print(item)

Cover
Cleaning cloth
Air freshener
Repair kit
Tire inflator
GPS
Tool kit


List comprehension can be used to create lists

In [ ]:
list(range(10)) # Creates a list from 0 to 10 (excluding the final term)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  print(i**2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
square_numbers = []  # Creating empty list

for i in range(10):
  square_numbers.append(i**2)

square_numbers

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Using list comprehension, this entire procedure can be performed using a single line

In [ ]:
square_numbers = [i**2 for i in range(10)]

square_numbers

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# Nested loops

In [ ]:
car_1 = ['Jetta', '4.0', 2003, 44410.0, False, [items[1], items[4], items[5]], 88078.64]
car_2 = ['Passat', 'Diesel', 1991, 5712.0, False, [items[0], items[2]], 106161.94]
cars = [car_1, car_2]
cars

[['Jetta',
  '4.0',
  2003,
  44410.0,
  False,
  ['Cleaning cloth', 'Tire inflator', 'GPS'],
  88078.64],
 ['Passat',
  'Diesel',
  1991,
  5712.0,
  False,
  ['Cover', 'Air freshener'],
  106161.94]]

In [ ]:
print(cars)

[['Jetta', '4.0', 2003, 44410.0, False, ['Cleaning cloth', 'Tire inflator', 'GPS'], 88078.64], ['Passat', 'Diesel', 1991, 5712.0, False, ['Cover', 'Air freshener'], 106161.94]]


In [ ]:
for car in cars:
  print(car)

['Jetta', '4.0', 2003, 44410.0, False, ['Cleaning cloth', 'Tire inflator', 'GPS'], 88078.64]
['Passat', 'Diesel', 1991, 5712.0, False, ['Cover', 'Air freshener'], 106161.94]


In [ ]:
for car in cars:        # In each iteration, read a car from the list  
  for data in car:      # In each iteration, read data for each car
    print(data)

Jetta
4.0
2003
44410.0
False
['Cleaning cloth', 'Tire inflator', 'GPS']
88078.64
Passat
Diesel
1991
5712.0
False
['Cover', 'Air freshener']
106161.94


Another example

In [ ]:
items_a = ['Cover', 'Air freshener', 'Repair kit', 'Tool kit']
items_b = ['Repair kit', 'GPS']
items_c = ['Cleaning cloth', 'Air freshener', 'Tire inflator']
items_list = [items_a, items_b, items_c]

In [ ]:
accessories = []

for items in items_list:
  for item in items:
    accessories.append(item)

accessories

['Cover',
 'Air freshener',
 'Repair kit',
 'Tool kit',
 'Repair kit',
 'GPS',
 'Cleaning cloth',
 'Air freshener',
 'Tire inflator']

To remove duplicates, we can use the set( ) function

In [ ]:
accessories = list(set(accessories))

We can also perform these operations using list comprehension

In [ ]:
acessories = list(set([item for items in items_list for item in items]))

acessories

['Repair kit',
 'GPS',
 'Cleaning cloth',
 'Tool kit',
 'Cover',
 'Air freshener',
 'Tire inflator']

# Conditionals

Conditionals can be used to add specific triggers to code

In [5]:
# index 1 - car name
# index 2 - year
# index 3 - is car 0 km?

data = [
        ['Jetta', 2003, False],
        ['Passat', 1991, False],
        ['Crossfox', 1990, False],
        ['DS5', 2019, True],
        ['Aston Martin DB4', 2006, False],
        ['Palio', 2012, False],
        ['A5', 2019, True],
        ['Cabrio S3', 2009, False],
        ['Dodge Journey', 2019, False],
        ['Carens', 2011, False]
]

We want to print the car name if it is new (0 km)

In [6]:
for car in data:
  if car[2] == True:
    print(f'{car[0]} is 0 km.')

DS5 is 0 km.
A5 is 0 km.


Using list comprehension

In [10]:
new_cars = [car[0] for car in data if car[2] == True]
new_cars

['DS5', 'A5']

# If-else-elif

These operators can be used to handle exceptions when dealing with conditionals.

In [13]:
new_cars = []
old_cars = []

for car in data:
  if car[2] == True:
    print(f'{car[0]} is 0 km.')
    new_cars.append(car[0])
  else:
    print(f'{car[0]} is not 0 km.')
    old_cars.append(car[0])

Jetta is not 0 km.
Passat is not 0 km.
Crossfox is not 0 km.
DS5 is 0 km.
Aston Martin DB4 is not 0 km.
Palio is not 0 km.
A5 is 0 km.
Cabrio S3 is not 0 km.
Dodge Journey is not 0 km.
Carens is not 0 km.


Elif can be used for more than two conditions

In [14]:
for car in data:
  if car[1] > 2015:
    print(f'{car[0]} was fabricated after 2015.')
  elif car[1] > 2005:
    print(f'{car[0]} was fabricated between 2005 and 2015.')
  elif car[1] > 1995:
    print(f'{car[0]} was fabricated between 1995 and 2005.')
  else:
    print(f'{car[0]} was fabricated before 1995.')

Jetta was fabricated between 1995 and 2005.
Passat was fabricated before 1995.
Crossfox was fabricated before 1995.
DS5 was fabricated after 2015.
Aston Martin DB4 was fabricated between 2005 and 2015.
Palio was fabricated between 2005 and 2015.
A5 was fabricated after 2015.
Cabrio S3 was fabricated between 2005 and 2015.
Dodge Journey was fabricated after 2015.
Carens was fabricated between 2005 and 2015.


Other important operators:

**and**: two conditions need to be satisfied

**or**: either condition need to be satisfied

In [15]:
for car in data:
  if car[1] <= 2000 and car[2] == False:
    print(f'{car[0]} is very old.')
  
  if car[1] > 2018 or car[2] == True:
    print(f'{car[0]} is in very good condition.')


Passat is very old.
Crossfox is very old.
DS5 is in very good condition.
A5 is in very good condition.
Dodge Journey is in very good condition.


# Numpy arrays

Finally, we will start working with numpy. Numpy is one of the most important python packages for handling numerical data. 

Numpy arrays are very similar to usual python lists.

In [16]:
import numpy as np

In [18]:
np.arange(10)  # Similar to range( ) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

One may create numpy arrays from a Python list

In [20]:
km_list  = [1000, 2300, 4987, 1500]

km_array = np.array(km_list)
km_array

array([1000, 2300, 4987, 1500])

We can check the type for the array

In [21]:
type(km_array)

numpy.ndarray

We can also check type of data inside the array

Important: data from numpy arrays must be of the same type!

In [22]:
km_array.dtype

dtype('int64')

Data from external files can also be turned into numpy arrays

In [29]:
km_array = np.loadtxt(fname = 'car_km.txt', dtype = int)
km_array

array([ 70000,  50000, 100000, ...,  83000,  90000,  40000])

We can also create arrays with multiple dimensions

In [31]:
data = [['Jetta', 2003, False],
        ['Passat', 1991, False],
        ['Crossfox', 1990, False],
        ['DS5', 2019, True],
        ['Aston Martin DB4', 2006, False],
        ['Palio', 2012, False],
        ['A5', 2019, True],
        ['Cabrio S3', 2009, False],
        ['Dodge Journey', 2019, False],
        ['Carens', 2011, False]]

data_array = np.array(data)
data_array

array([['Jetta', '2003', 'False'],
       ['Passat', '1991', 'False'],
       ['Crossfox', '1990', 'False'],
       ['DS5', '2019', 'True'],
       ['Aston Martin DB4', '2006', 'False'],
       ['Palio', '2012', 'False'],
       ['A5', '2019', 'True'],
       ['Cabrio S3', '2009', 'False'],
       ['Dodge Journey', '2019', 'False'],
       ['Carens', '2011', 'False']], dtype='<U21')

Array dimension (in this case, number of row and columns) can be found using shape

In [33]:
data_array.shape

(10, 3)

Comparing efficiency of numpy arrays and python base lists

In [34]:
np_array = np.arange(1000000)

In [35]:
py_list = list(range(1000000))

To compare execution times, we can use %time

In [36]:
%time for _ in range(100): np_array *= 2

CPU times: user 104 ms, sys: 610 µs, total: 104 ms
Wall time: 112 ms


In [37]:
%time for _ in range(100): py_list = [x*2 for x in py_list]

CPU times: user 9.47 s, sys: 2.38 s, total: 11.9 s
Wall time: 11.9 s


Note that execution with numpy arrays is much faster than using conventional Python lists.

# Operations with Numpy arrays

Numpy is a very strong tool for dealing with numerical data. Thus, the possibility of performing mathematical operations using numpy arrays is one of the main reasons to use this library.

In [38]:
km = [44410., 5712., 37123., 0., 25757.]
year = [2003, 1991, 1990, 2019, 2006]

We are not able to perform operations using conventional Python lists. First, we have to turn them into Numpy arrays.

Example: Calculating age of each car

In [41]:
km = np.array(km)
year = np.array(year)

curr_year = 2022
age = curr_year - year
age

array([19, 31, 32,  3, 16])

We can also perform operations between arrays

In [43]:
km_per_year = km/age # Division: index i with index i
km_per_year

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

Operations with multidimensional arrays

In [46]:
data = np.array([km, year])
data.shape

(2, 5)

In [48]:
km_per_year = data[0]/(curr_year - data[1])
km_per_year

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

Other example: calculating body mass index

In [51]:
height = [1.71, 1.82, 1.63, 1.67, 1.92, 1.69] # in meters
weight = [72, 78, 53, 67, 89, 82] # in kg
data = np.array([height, weight])

In [52]:
BMI = data[1]/(data[0]**2)
BMI

array([24.62296091, 23.54788069, 19.94805977, 24.02380867, 24.14279514,
       28.71047932])

# Indexing with Numpy arrays

Indexing with numpy arrays is very similar to usual Python lists

In [53]:
counter = np.arange(10)

In [55]:
counter[5]

5

In [56]:
counter[0]

0

In [57]:
counter[-1]

9

In [58]:
data[0]

array([1.71, 1.82, 1.63, 1.67, 1.92, 1.69])

In [59]:
data[0][2]

1.63

Using Numpy arrays, indexing can also be performed similar to Matlab, as shown in the following.

In [142]:
data[0,2]

1.63

Array slicing with Numpy arrays can have an additional argument, related to the step given

In [61]:
end_count = counter[6:]
end_count

array([6, 7, 8, 9])

In [63]:
counter_even = counter[0:10:2]
counter_even

array([0, 2, 4, 6, 8])

In [65]:
data[0][2:4]

array([1.63, 1.67])

Indexing with boolean arrays

In [70]:
good_weight = BMI < 24
good_weight

array([False,  True,  True, False, False, False])

We can use boolean arrays to assist in indexing

In [71]:
BMI[good_weight] # Only returns BMI[i] when good_weight[i] == True

array([23.54788069, 19.94805977])

# Methods and attributes using Numpy arrays

In [99]:
height = [1.71, 1.82, 1.63, 1.67, 1.92, 1.69] # in meters
weight = [72, 78, 53, 67, 89, 82] # in kg
data = np.array([height, weight])

**shape**: returns array dimensions

In [100]:
data.shape

(2, 6)

**ndim**: returns number of dimensions of the array

In [101]:
data.ndim

2

**size**: returns number of elements in the array

In [102]:
data.size

12

**dtype**: returns data type

In [103]:
data.dtype

dtype('float64')

**T**: transpose array

In [104]:
data

array([[ 1.71,  1.82,  1.63,  1.67,  1.92,  1.69],
       [72.  , 78.  , 53.  , 67.  , 89.  , 82.  ]])

In [105]:
data.T

array([[ 1.71, 72.  ],
       [ 1.82, 78.  ],
       [ 1.63, 53.  ],
       [ 1.67, 67.  ],
       [ 1.92, 89.  ],
       [ 1.69, 82.  ]])

Methods:

**tolist( )**: turns arrays to lists

In [106]:
data.tolist( )

[[1.71, 1.82, 1.63, 1.67, 1.92, 1.69], [72.0, 78.0, 53.0, 67.0, 89.0, 82.0]]

**reshape(shape[,order])**: returns array with the same data, but in a new shape



In [107]:
data

array([[ 1.71,  1.82,  1.63,  1.67,  1.92,  1.69],
       [72.  , 78.  , 53.  , 67.  , 89.  , 82.  ]])

In [108]:
data.reshape((4,3))

array([[ 1.71,  1.82,  1.63],
       [ 1.67,  1.92,  1.69],
       [72.  , 78.  , 53.  ],
       [67.  , 89.  , 82.  ]])

In [109]:
data.reshape((2, 6))

array([[ 1.71,  1.82,  1.63,  1.67,  1.92,  1.69],
       [72.  , 78.  , 53.  , 67.  , 89.  , 82.  ]])

**resize(new_shape[,refcheck])**: changes shape and size of the array

In [110]:
data.resize((3, 6), refcheck=False)

In [111]:
data

array([[ 1.71,  1.82,  1.63,  1.67,  1.92,  1.69],
       [72.  , 78.  , 53.  , 67.  , 89.  , 82.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [114]:
data[2] = data[1]/(data[0]**2)

In [115]:
data

array([[ 1.71      ,  1.82      ,  1.63      ,  1.67      ,  1.92      ,
         1.69      ],
       [72.        , 78.        , 53.        , 67.        , 89.        ,
        82.        ],
       [24.62296091, 23.54788069, 19.94805977, 24.02380867, 24.14279514,
        28.71047932]])

# Basic statistics using Numpy

In [125]:
car_year  = np.loadtxt(fname = 'car_year.txt', dtype = int)
car_km    = np.loadtxt(fname = 'car_km.txt', dtype = float)
car_price = np.loadtxt(fname = 'car_price.txt', dtype = float)

In [117]:
car_year.shape

(4340,)

In [118]:
car_km.shape

(4340,)

In [119]:
car_price.shape

(4340,)

Joining data

In [127]:
data_cars = np.array([car_year, car_km, car_price])
data_cars

array([[  2007.,   2007.,   2012., ...,   2009.,   2016.,   2016.],
       [ 70000.,  50000., 100000., ...,  83000.,  90000.,  40000.],
       [ 60000., 135000., 600000., ..., 110000., 865000., 225000.]])

Another way of performing the same procedure

In [130]:
dataset = np.row_stack((car_year, car_km, car_price))
dataset

array([[  2007.,   2007.,   2012., ...,   2009.,   2016.,   2016.],
       [ 70000.,  50000., 100000., ...,  83000.,  90000.,  40000.],
       [ 60000., 135000., 600000., ..., 110000., 865000., 225000.]])

In [131]:
dataset.shape

(3, 4340)

Evaluating mean values

In [133]:
np.mean(dataset, axis = 1) # axis = 1: mean is performed on rows! axis = 0: mean is performed on columns!

array([  2013.09078341,  66215.77741935, 504127.31175115])

Another way of performing a similar procedure

In [136]:
np.mean(dataset[1]) # mean km

66215.77741935484

In [137]:
np.mean(dataset[2]) # mean prices

504127.3117511521

Evaluating standard deviation

In [138]:
np.std(dataset[2])

578482.0792187806

Evaluating sum

In [139]:
np.sum(dataset[1])

287376474.0